repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--preview"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.10
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.3.3
          - prettier-plugin-tailwindcss@0.6.6
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
